---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ template "name" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        component: eventrouter
        tier: control-plane-addons
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter 
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      serviceAccount: {{ .Values.name }}
      volumes: 
        - name: config-volume
          configMap:
            name: {{ .Values.name }}-configmap
  
